#!/usr/bin/env bash
# Install script for Weather
# Written by: Hubert Léveillé Gauvin

cd weather-tool
cat xaa xab > city.list.json
rm xaa
rm xab
cd ..

cp weather.1 /usr/local/share/man/man1
mkdir /usr/local/weather-tool
cp  ./weather-tool/* /usr/local/weather-tool
cd /usr/local/weather-tool
echo "export PATH=$PATH:/usr/local/weather-tool" >> ~/.bash_profile
source ~/.bash_profile
